### ISSUE TITLE
Type 'typeof EventEmitter' is not a constructor function type.

### ISSUE THREAD

**Issue by teddybee** [curveball/core#138]
I have started a project with typescript. The tsc returns this error at compile:

node_modules/@curveball/core/dist/application.d.ts:26:42 - error TS2507: Type 'typeof EventEmitter' is not a constructor function type.

After little searching I found a solution. Could you fix this please?
[https://stackoverflow.com/questions/33572425/type-x-is-not-a-constructor-function-type-ts2507](https://stackoverflow.com/questions/33572425/type-x-is-not-a-constructor-function-type-ts2507)
I am using "typescript": "^3.8.3",  "@curveball/core": "^0.11.1".

Dev run is working without that error by "ts-node-dev": "^1.0.0-pre.44".

**Comment by evert** [comment]
Hi!

Are you using an unstable version of @types/node? I think this is a problem with the 13.* series.
Not sure if this something that will be fixed, but switching to a version of that package that matches your node version is regardless a good idea.

**Comment by evert** [comment]
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/41353

**Comment by teddybee** [comment]
Yes, "@types/node": "^13.9.0",

**Comment by evert** [comment]
I also committed a fix to help with this. You're not the first to run into this and there is a workaround. Going to release it shortly.
