### ISSUE TITLE
WebSockets on the same port as HTTP [Firefox/Chrome]

### ISSUE THREAD

**Issue by spidgorny** [curveball/core#159]
AFAIK it's possible to have WebSockets server on the same port as the normal HTTP server. However when I tried this I got mixed results.

Firefox: shows the correct '/' controller.
![image](https://user-images.githubusercontent.com/1579235/95619969-bd639600-0a6f-11eb-831f-fad070a0f219.png)

Chrome: shows "Upgrade Required" with HTTP status 406.
![image](https://user-images.githubusercontent.com/1579235/95620015-ceaca280-0a6f-11eb-8b7c-13dad828594b.png)

```
		const app = new Application();
		app.use(router('/', new IndexController(this.redis)));

		let port = parseInt(process.env.PORT!, 10);
		const server = http.createServer(app.callback());
		server.on('upgrade', app.upgradeCallback.bind(this));
		server.listen(port, '0.0.0.0');

		const serverWs = app.listenWs(port);
		this.socketController = new SocketController(serverWs);
		app.use(router('/socket', this.socketController));
```

I'm confused. Why would two browsers behave different? Anybody seen this before?

**Comment by evert** [comment]
Very weird, I don't know why this is happening :/

The intent is 100% to only need one `listen` call and get the websocket for free, but I didn't have the time to figure out how to do this elegantly. `listenWs` was really just a temporary measure to get the feature going until I was able to do this the right way.
