### ISSUE TITLE
Context not assignable to Middleware

### ISSUE THREAD

**Issue by defrex** [curveball/core#206]
In `@curveball/core@0.20.0`, I can't use the exported `Context` to define a middleware, else they will be incompatible. Since controllers are middleware, this also makes controllers type-incompatible with `route`.

```typescript
import { Context, Middleware } from '@curveball/core';

const exampleMiddleware: Middleware = async (ctx: Context, next) => null;
```

The above should work, but results in the following error.

```
Type '(ctx: Context<any, any>, next: () => Promise<void>) => Promise<null>' is not assignable to type 'Middleware'.
  Type '(ctx: Context<any, any>, next: () => Promise<void>) => Promise<null>' is not assignable to type 'MiddlewareFunction'.
    Types of parameters 'ctx' and 'ctx' are incompatible.
      Type 'Context<any, any>' is missing the following properties from type 'Context<any, any>': session, sessionId, getCsrf, validateCsrf, paramsts(2322)
```

The same error appears if both are imported from `@curveball/kernel` BTW, so that isn't a fix here.

<img width="705" alt="Screen Shot 2022-09-27 at 3 44 40 PM" src="https://user-images.githubusercontent.com/57580/192620993-9519564d-6ed8-498d-9fb5-ba5765fd961a.png">

**Comment by evert** [comment]
Is this still true with everything up to date? Usually this only happens if you somehow have a mixed set of packages with different versions.

**Comment by evert** [comment]
Looking at this list, i think we're at least missing a npm release for browser-to-bearer. 0.4.0 is the latest, but the publish action failed:

https://github.com/curveball/browser-to-bearer/actions/runs/2986071165

Gonna fix this

**Comment by evert** [comment]
This has a new release:

https://github.com/curveball/browser-to-bearer/releases/tag/v0.4.1

**Comment by evert** [comment]
@curveball/router in this list is also old. This is correctly released and I would say very likely the actual culprit.

**Comment by evert** [comment]
I'm 90% sure upgrading router will fix this, so closing this ticket with that premise. If I'm wrong, we can re-open.

**Comment by evert** [comment]
Pretty strange! You're not using some internal npm registry are you?

If you're willing to share package-lock, I could also take a look there. Also curious what is set in your own `package.json` for that dependency.
