### ISSUE TITLE
Allow many middlewares to be registered at once.

### ISSUE THREAD

**Issue by evert** [curveball/core#66]
Change signature of `use(mw: Middleware)` to `use(mw: Middleware|Middleware[])`

**Comment by Nimor111** [comment]
If this is till relevant i'd like to take a shot at it. 👍

**Comment by Nimor111** [comment]
Writing it as
```
app.use(mw1, mw2);
```

Seems more intuitive yes.

**Comment by craigmc08** [comment]
Shouldn't this be closed? It was implemented in #98.

**Comment by evert** [comment]
Yep you're right!
